method: grid
metric:
  goal: maximize
  name: normalized_scores_mean
parameters:
  num_checkpoints:
    values:
      - 0
  awac_lambda:
    values:
      - 1.0
      - 0.3
  frame_stack:
    values:
      - 1
      - 8
  include_previous_action:
    values:
      - False
      - True
program: awac.py

command:
  - python
  - ${program}
  - train
  - hp_sweeps/awac_sweep_config.yaml
