method: grid
metric:
  goal: maximize
  name: normalized_score_mean
parameters:
  num_checkpoints:
    values:
      - 0
  qf_lr:
    values:
      - 3e-5
  policy_lr:
    values:
      - 3e-4
  cql_target_action_gap:
    values:
      - 10.0
  cql_lagrange:
    values:
      - True
      - False
  temperature:
    values:
      - 0.3
      - 1.0
      - 3.0
  frame_stack:
    values:
      - 1
      - 8
  include_previous_action:
    values:
      - True
      - False
program: cql_sac.py
