method: grid
metric:
  goal: maximize
  name: normalized_score_mean
parameters:
  qf_lr:
    values:
      - 1e-4
      - 3e-5
  alpha:
    values:
      - 0.5
      - 1.0
      - 4.0
  frame_stack:
    values:
      - 1
      - 8
  include_previous_action:
    values:
      - True
      - False
program: cql.py
