method: grid
metric:
  goal: maximize
  name: normalized_score_mean
parameters:
  gamma:
    values:
      - 0.9
      - 0.5
      - 0.1
  qf_lr:
    values:
      - 1e-4
  alpha:
    values:
      - 0.1
      - 0.25
      - 0.5
  frame_stack:
    values:
      - 8
  include_previous_action:
    values:
      - True
program: algorithms/cql.py

command:
  - python
  - ${program}
  - train
  - algorithms/hp_sweeps/cql_sweep_config.yaml
