method: grid
metric:
  goal: maximize
  name: eval/normalized_score_mean
parameters:
  num_checkpoints:
    values:
      - 0
  num_critics:
    values:
      - 10
      - 55
      - 100
  eta:
    values:
      - 0.0
      - 1.0
      - 5.0
  temperature:
    values:
      - 0.25
      - 1.0
      - 4.0
  frame_stack:
    values:
      - 1
      - 8
  include_previous_action:
    values:
      - True
      - False
program: algorithms/edac.py

command:
  - python
  - ${program}
  - train
  - hp_sweeps/edac_sweep_config.yaml
