method: grid

metric:
  goal: maximize
  name: eval/normalized_score_mean
parameters:
  num_checkpoints:
    values:
      - 0
  num_critics:
    values:
      - 100
  eta:
    values:
      - 5.0
  temperature:
    values:
      - 4.0
  frame_stack:
    values:
      - 8
  include_previous_action:
    values:
      - False
program: edac.py
