method: random
metric:
  goal: maximize
  name: normalized_score
parameters:
  num_checkpoints:
    values:
      - null
  iql_tau:
    values:
      - 0.5
      - 0.7
      - 0.9
  beta:
    values:
      - 3.0
      - 6.0
      - 10.0
  temperature:
    distribution: log_uniform_values
    max: 10.0
    min: 0.1
  actor_dropout:
    values:
      - 0.0
      - 0.1
  frame_stack:
    values:
      - 1
      - 8
program: iql.py
