method: grid
metric:
  goal: maximize
  name: normalized_score
parameters:
  iql_tau:
    values:
      - 0.5
      - 0.7
      - 0.9
  beta:
    values:
      - 3.0
      - 6.0
      - 10.0
  actor_dropout:
    values:
      - 0.0
      - 0.1
  frame_stack:
    values:
      - 1
      - 8
  include_previous_action:
    values:
      - True
      - False
program: iql.py

command:
  - python
  - ${program}
  - train
  - hp_sweeps/iql_sweep_config.yaml
