method: grid
metric:
  goal: maximize
  name: mean_normalized_score
parameters:
  num_checkpoints:
    values:
      - 0
  alpha:
    values:
      - 1.0
      - 2.5
      - 4.0
  temperature:
    values:
      - 0.3
      - 1.0
      - 3.0
  frame_stack:
    values:
      - 1
      - 8
  include_previous_action:
    values:
      - True
      - False
program: algorithms/td3_bc.py

command:
  - python
  - ${program}
  - train
  - hp_sweeps/td3_bc_sweep_config.yaml
