method: grid
metric:
  goal: maximize
  name: normalized_score_mean
parameters:
  checkpoints_path:
    values:
      - checkpoints_restrict
  num_checkpoints:
    values:
      - 1
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
  episodes_avail:
    values:
      - 131072
      - 65536
      - 32768
      - 16384
      - 8192
      - 4096
      - 2048
      - 1024
      - 512
      - 256
      - 128
      - 64
      - 32
program: cql_sac.py
