method: grid
metric:
  goal: maximize
  name: normalized_score
parameters:
  checkpoints_path:
    values:
      - checkpoints_restrict
  num_checkpoints:
    values:
      - 1
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
  episodes_avail:
    values:
      - 131072
  eval_freq:
    values:
      - 500
  iql_tau:
    values:
      - 0.9
  beta:
    values:
      - 3.0
  actor_dropout:
    values:
      - 0.1
  frame_stack:
    values:
      - 8
  include_previous_action:
    values:
      - True
program: iql.py
