method: grid
metric:
  goal: maximize
  name: mean_normalized_score
parameters:
  checkpoints_path:
    values:
      - checkpoints_restrict
  num_checkpoints:
    values:
      - 1
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
  episodes_avail:
    values:
      - 131072
      - 65536
  alpha:
    values:
      - 4.0
  temperature:
    values:
      - 3.0
  frame_stack:
    values:
      - 8
  include_previous_action:
    values:
      - True
program: algorithms/td3_bc.py

command:
  - python
  - ${program}
  - train
  - data_restriction_sweeps/td3_bc_restriction_config.yaml
