method: grid
metric:
  goal: maximize
  name: normalized_scores_mean
parameters:
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
  awac_lambda:
    values:
      - 0.3
  include_previous_actions:
    values:
      - True
  frame_stack:
    values:
      - 8
  num_checkpoints:
    values:
      - 32
  behavior_policy:
    values:
      - "soc"
program: awac.py
