method: grid
metric:
  goal: maximize
  name: normalized_scores_mean
parameters:
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  awac_lambda:
    values:
      - 0.3
  include_previous_actions:
    values:
      - False
  frame_stack:
    values:
      - 8
  num_checkpoints:
    values:
      - 32
program: awac.py
