method: grid
metric:
  goal: maximize
  name: normalized_score_mean
parameters:
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
  alpha:
    values:
      - 1.0
  frame_stack:
    values:
      - 8
  include_previous_action:
    values:
      - True
  qf_lr:
    values:
      - 1e-4
  behavior_policy:
    values:
      - "smart"
  num_checkpoints:
    values:
      - 1
program: cql_dqn.py
