method: grid
metric:
  goal: maximize
  name: normalized_score_mean
parameters:
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  qf_lr:
    values:
      - 1e-4
  alpha:
    values:
      - 0.0
  frame_stack:
    values:
      - 8
  include_previous_action:
    values:
      - True
  behavior_policy:
    values:
      - "smart"
  num_checkpoints:
    values:
      - 32
program: algorithms/drn.py

command:
  - python
  - ${program}
  - train
  - all_data_sweeps/drn_final_config.yaml
