method: grid
metric:
  goal: maximize
  name: eval/normalized_score_mean
parameters:
  train_seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
  num_checkpoints:
    values:
      - 32
  num_critics:
    values:
      - 100
  eta:
    values:
      - 0.1
  temperature:
    values:
      - 4.0
  frame_stack:
    values:
      - 8
  include_previous_action:
    values:
      - True
  behavior_policy:
    values:
      - "smart"
program: edac.py
