method: grid
metric:
  goal: maximize
  name: normalized_score
parameters:
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
  num_checkpoints:
    values:
      - 1
  iql_tau:
    values:
      - 0.9
  beta:
    values:
      - 3.0
  actor_dropout:
    values:
      - 0.1
  frame_stack:
    values:
      - 8
  include_previous_action:
    values:
      - True
  behavior_policy:
    values:
      - "smart"
program: iql.py
