method: grid
metric:
  goal: maximize
  name: mean_normalized_score
parameters:
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  num_checkpoints:
    values:
      - 32
  alpha:
    values:
      - 4.0
  temperature:
    values:
      - 3.0
  frame_stack:
    values:
      - 8
  include_previous_action:
    values:
      - True
program: td3_bc.py
