method: grid
metric:
  goal: maximize
  name: eval/normalized_score_mean
parameters:
  train_seed:
    values:
      - 1
      - 2
      - 3
      - 4
  env_seed:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
program: edac.py
